import type { ProceduralArchetype } from './types';

export const ARCHETYPES: ProceduralArchetype[] = [
  {
    id: 'manual_intake',
    label: 'Prise en charge manuelle des demandes',
    description: 'Les demandes entrantes (clients, fournisseurs, internes) sont traitées manuellement, souvent par email ou téléphone, sans traçabilité centralisée.',
    trigger_signals: ['email', 'intake'],
    common_frictions: ['email_as_workflow', 'duplicate_entry', 'missing_visibility'],
    candidate_opportunities: ['structure_data_first', 'automate_bounded_step'],
  },
  {
    id: 'manual_reporting',
    label: 'Reporting reconstruit manuellement',
    description: 'Les tableaux de bord et rapports sont reconstruits à la main à partir de plusieurs sources, souvent dans un tableur.',
    trigger_signals: ['reporting', 'spreadsheet'],
    common_frictions: ['manual_reporting_rebuild', 'spreadsheet_dependency', 'slow_information_retrieval'],
    candidate_opportunities: ['structure_data_first', 'automate_bounded_step'],
  },
  {
    id: 'document_chasing',
    label: 'Recherche de documents dispersés',
    description: 'Les documents nécessaires au travail sont répartis dans plusieurs endroits (emails, dossiers, clés USB, papier) et difficiles à retrouver.',
    trigger_signals: ['document', 'email'],
    common_frictions: ['document_dispersion', 'slow_information_retrieval'],
    candidate_opportunities: ['structure_data_first', 'standardize_first'],
  },
  {
    id: 'multi_tool_coordination',
    label: 'Coordination entre plusieurs outils',
    description: 'L\'activité repose sur plusieurs outils non connectés entre eux, nécessitant des transferts manuels d\'information.',
    trigger_signals: ['multi_tool', 'spreadsheet'],
    common_frictions: ['duplicate_entry', 'spreadsheet_dependency', 'missing_visibility'],
    candidate_opportunities: ['structure_data_first', 'partial_workflow_automation'],
  },
  {
    id: 'manual_validation',
    label: 'Validation manuelle sans traçabilité',
    description: 'Les validations (devis, commandes, congés, achats) passent par des échanges informels sans trace ni circuit structuré.',
    trigger_signals: ['validation', 'email'],
    common_frictions: ['non_traceable_validation', 'email_as_workflow', 'manual_followup'],
    candidate_opportunities: ['partial_workflow_automation', 'assist_human_work'],
  },
  {
    id: 'data_reentry',
    label: 'Ressaisie de données entre systèmes',
    description: 'Les mêmes informations sont saisies plusieurs fois dans des outils différents (tableur, logiciel métier, facturation).',
    trigger_signals: ['duplicate_entry', 'spreadsheet'],
    common_frictions: ['duplicate_entry', 'spreadsheet_dependency'],
    candidate_opportunities: ['automate_bounded_step', 'structure_data_first'],
  },
  {
    id: 'exception_followup',
    label: 'Suivi des exceptions et relances',
    description: 'Les cas particuliers, retards et anomalies sont suivis manuellement, souvent par mémoire individuelle.',
    trigger_signals: ['followup', 'email'],
    common_frictions: ['manual_followup', 'single_person_dependency', 'missing_visibility'],
    candidate_opportunities: ['assist_human_work', 'automate_bounded_step'],
  },
  {
    id: 'planning_dispatch',
    label: 'Planification et dispatch manuels',
    description: 'La planification des tâches, chantiers ou interventions est faite manuellement, souvent par une seule personne.',
    trigger_signals: ['planning', 'dependency'],
    common_frictions: ['single_person_dependency', 'missing_visibility'],
    candidate_opportunities: ['assist_human_work', 'standardize_first'],
  },
  {
    id: 'document_generation',
    label: 'Génération manuelle de documents',
    description: 'Les documents (devis, contrats, rapports) sont créés manuellement à partir de modèles ou de zéro.',
    trigger_signals: ['generation', 'document'],
    common_frictions: ['duplicate_entry', 'slow_information_retrieval'],
    candidate_opportunities: ['automate_bounded_step', 'standardize_first'],
  },
  {
    id: 'master_data_update',
    label: 'Mise à jour manuelle des données de référence',
    description: 'Les données de référence (clients, produits, tarifs) sont maintenues manuellement dans plusieurs endroits.',
    trigger_signals: ['master_data', 'spreadsheet'],
    common_frictions: ['duplicate_entry', 'spreadsheet_dependency', 'missing_visibility'],
    candidate_opportunities: ['structure_data_first', 'standardize_first'],
  },
];
